#ifndef __INC_METIN2_COMMON_DEFINES_H__
#define __INC_METIN2_COMMON_DEFINES_H__
#pragma once
#define _IMPROVED_PACKET_ENCRYPTION_
#define __PET_SYSTEM__
#define __UDP_BLOCK__
#define ENABLE_HIDE_COSTUME_SYSTEM
#define ENABLE_HIDE_COSTUME_SYSTEM_ACCE
#define ENABLE_HIDE_COSTUME_SYSTEM_WEAPON_COSTUME
#define ENABLE_D_NJGUILD
#define ENABLE_FULL_NOTICE
#define ENABLE_NEWSTUFF
#define ENABLE_PORT_SECURITY
#define ENABLE_BELT_INVENTORY_EX
#define ENABLE_CMD_WARP_IN_DUNGEON
#define ENABLE_PLAYER_PER_ACCOUNT5
#define ENABLE_DICE_SYSTEM
#define ENABLE_EXTEND_INVEN_SYSTEM
#define ENABLE_MOUNT_COSTUME_SYSTEM
#define ENABLE_WEAPON_COSTUME_SYSTEM
#define ENABLE_QUEST_DIE_EVENT
#define ENABLE_QUEST_BOOT_EVENT
#define ENABLE_QUEST_DND_EVENT
enum eCommonDefines {
	MAP_ALLOW_LIMIT = 32,
};
//#define ENABLE_WOLFMAN_CHARACTER
#define DISABLE_STOP_RIDING_WHEN_DIE
#define ENABLE_ACCE_COSTUME_SYSTEM
#define ENABLE_HIGHLIGHT_NEW_ITEM
#define __ENABLE_KILL_EVENT_FIX__
#endif
// GameCore.top
